#define dinPin 12
#define potPin A2
#define clockPin 11
#define loadPin 3
#define buzzerPin 10
#define brightPin 6
#define RS 13
#define enable 7
#define d4 5
#define d5 4
#define d6 9
#define d7 8
#define xPin A0
#define yPin A1
#define matrixSize 8
#define highScoreSize 3
#define settingsSize 5
#define minThreshold 200
#define maxThreshold 600
#define menuSize 4
#define swPin 2
#define showGreetingInterval 5000
#define aboutInterval 500
#define scoreStep 2
#define brightnessUpperLimit 240
#define brightnessStep 10
#define debounceInterval 200
#define showFigureInterval 5000
#define figuresNumber 12
#define numberOfCoord 12
#define nameSize 4
#define alphabetSize 26
#define buzzerPin 13